version: "3.1"

services: 
  jenkins-astro:
    container_name: jenkins-astro2
    build:
      context: . 
    image: jenkins-astro 
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "./jobs:/var/jenkins_home/jobs/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    secrets:
      - dockerhubPassword
secrets:
  dockerhubPassword:
    file: ./secrets/dockerhubPassword
